### ISSUE TITLE
在VS2017 15.6.4下，这个项目如何才能编译成功？

### ISSUE THREAD

**Issue by toddfsy** [cuteant/dotnetty-net40-fork#1]
如题

**Comment by cuteant** [comment]
下载  https://github.com/cuteant/CuteAnt.Extensions.Common ，跟dotnet同级目录就可以，还有单元测试我添加了 .netcoreapp2.1了，需要安装 .netcore2.1的sdk，再这儿下载 https://github.com/dotnet/cli
